const express=require('express')
const helmet=require('helmet')
const cors=require('cors')
const {allowedOrigins}=require('./config/env')
const {generalLimiter,attemptLimiter}=require('./middleware/rateLimiters')
const participantRoutes=require('./routes/participantRoutes')
const quizRoutes=require('./routes/quizRoutes')
const attemptRoutes=require('./routes/attemptRoutes')
const resultRoutes=require('./routes/resultRoutes')
const {notFound}=require('./middleware/notFound')
const {errorHandler}=require('./middleware/errorHandler')

const app=express()
app.disable('x-powered-by')
app.set('trust proxy',1)
app.use(helmet())
app.use(cors({origin:(origin,callback)=>{if(!origin||allowedOrigins.includes(origin))return callback(null,true);return callback(new Error('CORS origin not allowed'))},credentials:false}))
app.use(express.json({limit:'100kb'}))
app.use(generalLimiter)
app.get('/health',(req,res)=>res.json({success:true,data:{service:'apna-academy-quiz-api',status:'ok',timestamp:new Date().toISOString()}}))
app.use('/api/v1/participants',participantRoutes)
app.use('/api/v1/quizzes',quizRoutes)
app.use('/api/v1/attempts',attemptLimiter,attemptRoutes)
app.use('/api/v1/results',resultRoutes)
app.use(notFound)
app.use(errorHandler)
module.exports=app
