import { useEffect, useState } from "react";
import { Alert, Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, Paper, Snackbar, Stack, TextField, Tooltip, Typography } from "@mui/material";
import { Add, DeleteOutline, EditOutlined, Refresh, Search } from "@mui/icons-material";
import { archiveDsaProblem, createDsaProblem, listDsaProblems, updateDsaProblem } from "../services/dsaAdmin.service";
import { getApiErrorMessage } from "../services/api";

const initial={title:"",slug:"",description:"",difficulty:"Easy",topics:"",companies:"",patterns:"",constraints:"",hints:"",editorial:"",solution:"",starterCode:"",supportedLanguages:"Java,C++,Python,JavaScript",timeLimit:2,memoryLimit:256,isPremium:true,status:"DRAFT",order:1};
const csv=v=>v.split(",").map(x=>x.trim()).filter(Boolean);
const formOf=x=>({...initial,...x,topics:Array.isArray(x.topics)?x.topics.join(", "):x.topics||"",companies:Array.isArray(x.companies)?x.companies.join(", "):x.companies||"",patterns:Array.isArray(x.patterns)?x.patterns.join(", "):x.patterns||"",supportedLanguages:Array.isArray(x.supportedLanguages)?x.supportedLanguages.join(", "):x.supportedLanguages||initial.supportedLanguages});
const body=f=>({...f,title:f.title.trim(),slug:f.slug.trim(),topics:csv(f.topics),companies:csv(f.companies),patterns:csv(f.patterns),supportedLanguages:csv(f.supportedLanguages),order:Number(f.order)||1,timeLimit:Number(f.timeLimit)||2,memoryLimit:Number(f.memoryLimit)||256});

export default function DsaProblems(){
 const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[difficulty,setDifficulty]=useState(""),[status,setStatus]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(initial),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>{try{setLoading(true);const d=await listDsaProblems({page:1,limit:100,search,difficulty,status});setItems(d?.problems||d?.items||[])}catch(e){setError(getApiErrorMessage(e,"Unable to load DSA problems."))}finally{setLoading(false)}};
 useEffect(()=>{load()},[search,difficulty,status]);
 const save=async()=>{try{setSaving(true);if(editing)await updateDsaProblem(editing.id||editing._id,body(form));else await createDsaProblem(body(form));setOpen(false);setNotice(editing?"Problem updated successfully.":"Problem created successfully.");await load()}catch(e){setError(getApiErrorMessage(e,"Unable to save problem."))}finally{setSaving(false)}};
 const archive=async x=>{if(!window.confirm("Archive this DSA problem?"))return;try{await archiveDsaProblem(x.id||x._id);setNotice("Problem archived.");await load()}catch(e){setError(getApiErrorMessage(e,"Unable to archive problem."))}};
 const set=(k,v)=>setForm(p=>({...p,[k]:v}));
 return <Box className="min-h-screen bg-slate-50 p-4 sm:p-6 lg:p-8"><Stack direction={{xs:"column",md:"row"}} justifyContent="space-between" spacing={2} className="mb-6"><div><Typography variant="h4" className="font-extrabold tracking-tight">DSA Problem Management</Typography><Typography className="mt-1 text-slate-500">Create, edit, publish and archive coding problems.</Typography></div><Button variant="contained" startIcon={<Add/>} onClick={()=>{setEditing(null);setForm({...initial,order:items.length+1});setOpen(true)}}>New Problem</Button></Stack>
 <Paper elevation={0} className="overflow-hidden rounded-2xl border border-slate-200"><div className="flex flex-col gap-3 border-b border-slate-100 bg-white p-4 md:flex-row"><TextField size="small" fullWidth placeholder="Search title, topic or company..." value={search} onChange={e=>setSearch(e.target.value)} InputProps={{startAdornment:<Search className="mr-2 text-slate-400" fontSize="small"/>}}/><TextField size="small" select label="Difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)} className="md:w-40"><MenuItem value="">All</MenuItem><MenuItem value="Easy">Easy</MenuItem><MenuItem value="Medium">Medium</MenuItem><MenuItem value="Hard">Hard</MenuItem></TextField><TextField size="small" select label="Status" value={status} onChange={e=>setStatus(e.target.value)} className="md:w-40"><MenuItem value="">All</MenuItem><MenuItem value="DRAFT">Draft</MenuItem><MenuItem value="REVIEW">Review</MenuItem><MenuItem value="PUBLISHED">Published</MenuItem><MenuItem value="ARCHIVED">Archived</MenuItem></TextField><Tooltip title="Refresh"><IconButton onClick={load}><Refresh/></IconButton></Tooltip></div>
 {loading?<Box className="grid place-items-center py-20"><CircularProgress/></Box>:items.length===0?<Box className="py-20 text-center"><Typography className="font-bold">No DSA problems found</Typography><Typography variant="body2" className="text-slate-400">Create the first problem to start the library.</Typography></Box>:<div className="divide-y divide-slate-100">{items.map(x=><div key={x.id||x._id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><Typography className="font-extrabold">{x.title}</Typography><Chip size="small" label={x.difficulty||"Easy"}/><Chip size="small" label={x.isPremium?"Premium":"Free"} color={x.isPremium?"primary":"success"}/><Chip size="small" label={x.status||"DRAFT"}/></div><Typography variant="caption" className="text-slate-400">/{x.slug||"no-slug"} · {(x.topics||[]).slice(0,4).join(" · ")}</Typography></div><Stack direction="row"><Tooltip title="Edit"><IconButton onClick={()=>{setEditing(x);setForm(formOf(x));setOpen(true)}}><EditOutlined/></IconButton></Tooltip><Tooltip title="Archive"><IconButton color="error" onClick={()=>archive(x)}><DeleteOutline/></IconButton></Tooltip></Stack></div>)}</div>}</Paper>
 <Dialog open={open} onClose={()=>!saving&&setOpen(false)} fullWidth maxWidth="md"><DialogTitle>{editing?"Edit DSA Problem":"Create DSA Problem"}</DialogTitle><DialogContent dividers><div className="grid gap-4 pt-2 md:grid-cols-2">{[["title","Title"],["slug","Slug"],["topics","Topics (comma separated)"],["companies","Companies (comma separated)"],["patterns","Patterns (comma separated)"],["supportedLanguages","Supported languages"]].map(([k,l])=><TextField key={k} label={l} value={form[k]} onChange={e=>set(k,e.target.value)}/>)}<TextField select label="Difficulty" value={form.difficulty} onChange={e=>set("difficulty",e.target.value)}><MenuItem value="Easy">Easy</MenuItem><MenuItem value="Medium">Medium</MenuItem><MenuItem value="Hard">Hard</MenuItem></TextField><TextField select label="Status" value={form.status} onChange={e=>set("status",e.target.value)}><MenuItem value="DRAFT">Draft</MenuItem><MenuItem value="REVIEW">Review</MenuItem><MenuItem value="PUBLISHED">Published</MenuItem><MenuItem value="ARCHIVED">Archived</MenuItem></TextField><TextField label="Order" type="number" value={form.order} onChange={e=>set("order",e.target.value)}/><TextField label="Time limit (seconds)" type="number" value={form.timeLimit} onChange={e=>set("timeLimit",e.target.value)}/><TextField label="Memory limit (MB)" type="number" value={form.memoryLimit} onChange={e=>set("memoryLimit",e.target.value)}/><TextField label="Constraints" multiline minRows={3} value={form.constraints} onChange={e=>set("constraints",e.target.value)}/><TextField label="Description" multiline minRows={5} className="md:col-span-2" value={form.description} onChange={e=>set("description",e.target.value)}/><TextField label="Hints" multiline minRows={3} value={form.hints} onChange={e=>set("hints",e.target.value)}/><TextField label="Editorial" multiline minRows={3} value={form.editorial} onChange={e=>set("editorial",e.target.value)}/><TextField label="Solution" multiline minRows={3} value={form.solution} onChange={e=>set("solution",e.target.value)}/><TextField label="Starter code" multiline minRows={6} className="md:col-span-2" value={form.starterCode} onChange={e=>set("starterCode",e.target.value)}/><label className="md:col-span-2 flex items-center gap-3 rounded-xl border p-3 text-sm font-bold"><input type="checkbox" checked={form.isPremium} onChange={e=>set("isPremium",e.target.checked)}/> Premium problem (80% premium library)</label></div></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" disabled={saving||!form.title.trim()||!form.slug.trim()} onClick={save}>{saving?"Saving...":editing?"Update":"Create"}</Button></DialogActions></Dialog>
 <Snackbar open={Boolean(notice)} autoHideDuration={3000} onClose={()=>setNotice("")}><Alert severity="success">{notice}</Alert></Snackbar><Snackbar open={Boolean(error)} autoHideDuration={5000} onClose={()=>setError("")}><Alert severity="error">{error}</Alert></Snackbar></Box>;
}
