import { useEffect, useState } from "react";
import { Alert, Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Paper, Select, Stack, TextField, Typography } from "@mui/material";
import { Add, DeleteOutline, EditOutlined, Refresh, Search, ToggleOn } from "@mui/icons-material";
import { getApiErrorMessage } from "../services/api";
import { createAdminPromoCode, deleteAdminPromoCode, getAdminPromoCode, listAdminPromoCodes, toggleAdminPromoCode, updateAdminPromoCode } from "../services/adminPromoCode.service";
import { listAdminCourses } from "../services/adminCourse.service";

const empty = { code:"", description:"", discountType:"percentage", discountValue:"", maxDiscountAmount:"", minPurchaseAmount:"0", usageLimit:"", perUserLimit:"1", startsAt:"", expiresAt:"", applicableCourses:[], applicableCategories:"", isActive:true };
const localDate = (v) => v ? new Date(v).toISOString().slice(0,16) : "";
const formOf = (p) => ({ code:p.code||"", description:p.description||"", discountType:p.discountType||"percentage", discountValue:p.discountValue??"", maxDiscountAmount:p.maxDiscountAmount??"", minPurchaseAmount:p.minPurchaseAmount??0, usageLimit:p.usageLimit??"", perUserLimit:p.perUserLimit??1, startsAt:localDate(p.startsAt), expiresAt:localDate(p.expiresAt), applicableCourses:p.applicableCourses||[], applicableCategories:(p.applicableCategories||[]).join(", "), isActive:Boolean(p.isActive) });
const bodyOf = (f) => ({ code:f.code.trim().toUpperCase(), description:f.description.trim(), discountType:f.discountType, discountValue:Number(f.discountValue), maxDiscountAmount:f.discountType==="percentage"&&f.maxDiscountAmount!==""?Number(f.maxDiscountAmount):null, minPurchaseAmount:Number(f.minPurchaseAmount||0), usageLimit:f.usageLimit===""?null:Number(f.usageLimit), perUserLimit:Number(f.perUserLimit), startsAt:f.startsAt?new Date(f.startsAt).toISOString():new Date().toISOString(), expiresAt:f.expiresAt?new Date(f.expiresAt).toISOString():null, applicableCourses:f.applicableCourses, applicableCategories:f.applicableCategories.split(",").map(x=>x.trim()).filter(Boolean), isActive:f.isActive });

export default function PromoCodes(){
 const [rows,setRows]=useState([]),[courses,setCourses]=useState([]),[pagination,setPagination]=useState({page:1,limit:20,total:0,totalPages:1}),[search,setSearch]=useState(""),[active,setActive]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(empty),[saving,setSaving]=useState(false),[details,setDetails]=useState(null);
 const load=async(page=1)=>{try{setLoading(true);setError("");const d=await listAdminPromoCodes({page,limit:20,search,active});setRows(d.promos||[]);setPagination(d.pagination||pagination)}catch(e){setError(getApiErrorMessage(e,"Unable to load promo codes."))}finally{setLoading(false)}};
 useEffect(()=>{load(1)},[search,active]); useEffect(()=>{listAdminCourses({page:1,limit:100}).then(d=>setCourses(d?.courses||[])).catch(e=>setError(getApiErrorMessage(e,"Unable to load courses.")))},[]);
 const save=async()=>{try{setSaving(true);await (editing?updateAdminPromoCode(editing.id,bodyOf(form)):createAdminPromoCode(bodyOf(form)));setOpen(false);setEditing(null);setForm(empty);setNotice(editing?"Promo code updated.":"Promo code created.");await load(pagination.page)}catch(e){setError(getApiErrorMessage(e,"Unable to save promo code."))}finally{setSaving(false)}};
 const toggle=async(r)=>{try{const d=await toggleAdminPromoCode(r.id,!r.isActive);setRows(x=>x.map(y=>y.id===d.id?d:y));setNotice(d.isActive?"Promo activated.":"Promo deactivated.")}catch(e){setError(getApiErrorMessage(e,"Unable to change promo status."))}};
 const remove=async(r)=>{if(!window.confirm("Delete "+r.code+"? Used or reserved promos must be deactivated instead."))return;try{await deleteAdminPromoCode(r.id);setNotice("Promo deleted.");await load(pagination.page)}catch(e){setError(getApiErrorMessage(e,"Unable to delete promo."))}};
 return <Box className="p-4 sm:p-6 lg:p-8 max-w-[1600px] mx-auto"><Box className="mb-7 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><Box><Typography variant="h4" className="font-extrabold tracking-tight">Promo Codes</Typography><Typography className="mt-1 text-slate-500">Create, control and monitor course discount codes.</Typography></Box><Button variant="contained" startIcon={<Add/>} onClick={()=>{setEditing(null);setForm({...empty,startsAt:localDate(new Date())});setOpen(true)}}>New Promo</Button></Box>
 {error&&<Alert severity="error" className="mb-5" onClose={()=>setError("")}>{error}</Alert>}{notice&&<Alert severity="success" className="mb-5" onClose={()=>setNotice("")}>{notice}</Alert>}
 <Paper elevation={0} className="rounded-2xl border border-slate-200 p-4 mb-5"><div className="grid grid-cols-1 md:grid-cols-[1fr_180px_auto] gap-3"><TextField size="small" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search promo code" InputProps={{startAdornment:<Search className="mr-2 text-slate-400" fontSize="small"/>}}/><FormControl size="small"><InputLabel>Status</InputLabel><Select label="Status" value={active} onChange={e=>setActive(e.target.value)}><MenuItem value="">All</MenuItem><MenuItem value="true">Active</MenuItem><MenuItem value="false">Inactive</MenuItem></Select></FormControl><Button variant="outlined" startIcon={<Refresh/>} onClick={()=>load(pagination.page)}>Refresh</Button></div></Paper>
 <Paper elevation={0} className="rounded-2xl border border-slate-200 overflow-hidden">{loading?<Box className="py-24 grid place-items-center"><CircularProgress/></Box>:rows.length===0?<Box className="py-24 text-center text-slate-500">No promo codes found.</Box>:<Box className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left"><thead className="bg-slate-50 border-b border-slate-200"><tr>{["Code","Discount","Usage","Validity","Status","Actions"].map(x=><th key={x} className="px-5 py-4 text-xs font-bold uppercase tracking-wide text-slate-500">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.id}><td className="px-5 py-4"><Typography className="font-extrabold">{r.code}</Typography><Typography variant="caption" className="text-slate-500">{r.description||"No description"}</Typography></td><td className="px-5 py-4">{r.discountType==="percentage"?r.discountValue+"%":"₹"+r.discountValue}{r.maxDiscountAmount&&<Typography variant="caption" className="block text-slate-500">cap ₹{r.maxDiscountAmount}</Typography>}</td><td className="px-5 py-4"><Typography className="font-semibold">{r.usedCount}{r.usageLimit==null?" / ∞":" / "+r.usageLimit}</Typography><Typography variant="caption" className="text-slate-500">{r.reservedCount} reserved</Typography></td><td className="px-5 py-4 text-sm">{new Date(r.startsAt).toLocaleString()}<br/>{r.expiresAt?"to "+new Date(r.expiresAt).toLocaleString():"No expiry"}</td><td className="px-5 py-4"><Chip size="small" label={r.isActive?"Active":"Inactive"} color={r.isActive?"success":"default"}/></td><td className="px-5 py-4"><Stack direction="row" spacing={.5}><Button size="small" onClick={()=>getAdminPromoCode(r.id).then(setDetails).catch(e=>setError(getApiErrorMessage(e,"Unable to load details.")))}>Details</Button><Button size="small" startIcon={<EditOutlined/>} onClick={()=>{setEditing(r);setForm(formOf(r));setOpen(true)}}>Edit</Button><Button size="small" startIcon={<ToggleOn/>} onClick={()=>toggle(r)}>{r.isActive?"Off":"On"}</Button><Button size="small" color="error" startIcon={<DeleteOutline/>} onClick={()=>remove(r)}>Delete</Button></Stack></td></tr>)}</tbody></table></Box>}<Box className="flex items-center justify-between border-t border-slate-200 px-5 py-4"><Typography variant="body2" className="text-slate-500">{pagination.total} promo codes</Typography><Stack direction="row"><Button disabled={pagination.page<=1} onClick={()=>load(pagination.page-1)}>Previous</Button><Button disabled={pagination.page>=pagination.totalPages} onClick={()=>load(pagination.page+1)}>Next</Button></Stack></Box></Paper>
 <PromoDialog open={open} onClose={()=>!saving&&setOpen(false)} form={form} setForm={setForm} courses={courses} saving={saving} editing={editing} onSave={save}/>
 <Dialog open={Boolean(details)} onClose={()=>setDetails(null)} fullWidth maxWidth="md"><DialogTitle className="font-extrabold">Promo Details</DialogTitle><DialogContent dividers>{details&&<Stack spacing={3}><Paper elevation={0} className="rounded-xl border border-slate-200 p-4"><Typography variant="h5" className="font-extrabold">{details.promo.code}</Typography><Typography className="text-slate-500">{details.promo.description||"No description"}</Typography><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4"><Stat label="Used" value={details.promo.usedCount}/><Stat label="Reserved" value={details.promo.reservedCount}/><Stat label="Limit" value={details.promo.usageLimit??"∞"}/><Stat label="Per user" value={details.promo.perUserLimit}/></div></Paper><Typography variant="subtitle1" className="font-bold">Recent redemptions</Typography>{details.redemptions.length?details.redemptions.map(x=><Box key={x.id} className="rounded-xl border border-slate-200 p-3"><Typography className="font-semibold">{x.user?.name||x.user?.email||"User"} · {x.course?.title||"Course"}</Typography><Typography variant="body2" className="text-slate-500">Saved ₹{x.discountAmount} · Paid ₹{x.finalAmount} · {new Date(x.redeemedAt).toLocaleString()}</Typography></Box>):<Typography className="text-slate-500">No redemptions yet.</Typography>}</Stack>}</DialogContent><DialogActions><Button onClick={()=>setDetails(null)}>Close</Button></DialogActions></Dialog></Box>;
}
function Stat({label,value}){return <Box className="rounded-xl bg-slate-50 p-3"><Typography variant="caption" className="text-slate-500">{label}</Typography><Typography className="font-extrabold">{value}</Typography></Box>}
function PromoDialog({open,onClose,form,setForm,courses,saving,editing,onSave}){const u=(k,v)=>setForm(p=>({...p,[k]:v}));return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md"><DialogTitle className="font-extrabold">{editing?"Edit Promo":"Create Promo"}</DialogTitle><DialogContent dividers><div className="grid grid-cols-1 md:grid-cols-2 gap-4 py-1"><TextField label="Promo code *" value={form.code} onChange={e=>u("code",e.target.value.toUpperCase())} inputProps={{maxLength:50}}/><FormControl fullWidth><InputLabel>Discount type</InputLabel><Select label="Discount type" value={form.discountType} onChange={e=>u("discountType",e.target.value)}><MenuItem value="percentage">Percentage</MenuItem><MenuItem value="fixed">Fixed (₹)</MenuItem></Select></FormControl><TextField label="Discount value *" type="number" value={form.discountValue} onChange={e=>u("discountValue",e.target.value)}/>{form.discountType==="percentage"&&<TextField label="Maximum discount (₹)" type="number" value={form.maxDiscountAmount} onChange={e=>u("maxDiscountAmount",e.target.value)}/>}<TextField label="Minimum purchase (₹)" type="number" value={form.minPurchaseAmount} onChange={e=>u("minPurchaseAmount",e.target.value)}/><TextField label="Total usage limit" type="number" value={form.usageLimit} onChange={e=>u("usageLimit",e.target.value)} helperText="Empty = unlimited"/><TextField label="Per-user limit" type="number" value={form.perUserLimit} onChange={e=>u("perUserLimit",e.target.value)}/><TextField label="Start" type="datetime-local" value={form.startsAt} onChange={e=>u("startsAt",e.target.value)} InputLabelProps={{shrink:true}}/><TextField label="Expiry" type="datetime-local" value={form.expiresAt} onChange={e=>u("expiresAt",e.target.value)} InputLabelProps={{shrink:true}}/><TextField label="Description" value={form.description} onChange={e=>u("description",e.target.value)} multiline minRows={3} className="md:col-span-2"/><TextField label="Applicable categories" value={form.applicableCategories} onChange={e=>u("applicableCategories",e.target.value)} helperText="Comma-separated; empty = all categories" className="md:col-span-2"/><FormControl fullWidth className="md:col-span-2"><InputLabel>Applicable courses</InputLabel><Select multiple label="Applicable courses" value={form.applicableCourses} onChange={e=>u("applicableCourses",e.target.value)} renderValue={v=>v.length?v.length+" course(s) selected":"All courses"}>{courses.map(c=><MenuItem key={c.id} value={c.id}>{c.title}</MenuItem>)}</Select></FormControl></div><Box className="mt-4"><Chip label={form.isActive?"Active":"Inactive"} color={form.isActive?"success":"default"} onClick={()=>u("isActive",!form.isActive)}/></Box></DialogContent><DialogActions><Button onClick={onClose} disabled={saving}>Cancel</Button><Button variant="contained" onClick={onSave} disabled={saving||!form.code.trim()||!form.discountValue}>{saving?<CircularProgress size={20}/>:"Save Promo"}</Button></DialogActions></Dialog>}
