import { useCallback, useEffect, useState } from "react";
import { Alert, Box, Button, CircularProgress, Paper, Stack, Typography } from "@mui/material";
import { Refresh, DownloadOutlined, HistoryOutlined } from "@mui/icons-material";
import { getApiErrorMessage } from "../services/api";
import { getPromoAnalytics, getPromoAudit } from "../services/promoAnalytics.service";
const money=(v)=>"₹"+Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:2});
const num=(v)=>Number(v||0).toLocaleString("en-IN");
const presets=[["7","7 Days"],["30","30 Days"],["90","90 Days"],["180","6 Months"],["365","1 Year"]];
export default function PromoAnalytics(){
 const [data,setData]=useState(null),[audit,setAudit]=useState([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(""),[days,setDays]=useState("30");
 const load=useCallback(async(silent=false)=>{try{silent?setRefreshing(true):setLoading(true);setError("");const to=new Date();const from=new Date(to.getTime()-Number(days)*86400000);const [a,e]=await Promise.all([getPromoAnalytics({from:from.toISOString(),to:to.toISOString()}),getPromoAudit({limit:20})]);setData(a);setAudit(e.events||[])}catch(e){setError(getApiErrorMessage(e,"Unable to load promo analytics."))}finally{setLoading(false);setRefreshing(false)}},[days]);
 useEffect(()=>{load()},[load]);
 const exportCsv=()=>{if(!data)return;const rows=[["Metric","Value"],["Total promos",data.overview.totalPromos],["Active promos",data.overview.activePromos],["Redemptions",data.overview.redemptions],["Unique users",data.overview.uniqueUsers],["Discount given",data.overview.discountAmount],["Gross order amount",data.overview.grossOrderAmount],["Final paid amount",data.overview.finalPaidAmount],[],["Top Promo","Redemptions","Discount","Final Paid"],...(data.topCodes||[]).map(x=>[x.code,x.redemptions,x.discountAmount,x.finalAmount])];const csv=rows.map(r=>r.map(x=>"\""+String(x??"").replaceAll("\"","\"\"")+"\"").join(",")).join("\n");const u=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=u;a.download="apnaacademy-promo-analytics.csv";a.click();URL.revokeObjectURL(u)};
 if(loading&&!data)return <Box className="min-h-[70vh] grid place-items-center"><CircularProgress/></Box>;
 const o=data?.overview||{};
 return <Box className="min-h-screen bg-slate-50 p-4 sm:p-6 lg:p-8"><Box className="mx-auto max-w-7xl"><header className="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><Box><Typography variant="h4" className="font-extrabold tracking-tight">Promo Analytics & Audit</Typography><Typography className="mt-1 text-slate-500">Immutable redemption metrics and administrator activity.</Typography></Box><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<DownloadOutlined/>} onClick={exportCsv}>Export CSV</Button><Button variant="outlined" startIcon={<Refresh/>} disabled={refreshing} onClick={()=>load(true)}>Refresh</Button></Stack></header>
 {error&&<Alert severity="error" className="mb-5" onClose={()=>setError("")}>{error}</Alert>}
 <Paper elevation={0} className="rounded-2xl border border-slate-200 p-4 mb-5"><div className="flex flex-wrap gap-2">{presets.map(([v,l])=><button key={v} onClick={()=>setDays(v)} className={"rounded-xl border px-4 py-2 text-xs font-bold "+(days===v?"border-blue-600 bg-blue-600 text-white":"border-slate-200 bg-white text-slate-600")}>{l}</button>)}</div></Paper>
 <div className="grid grid-cols-2 gap-4 lg:grid-cols-4 mb-5">{[["Total Promos",o.totalPromos],["Active",o.activePromos],["Redemptions",o.redemptions],["Unique Users",o.uniqueUsers]].map(([l,v])=><Paper key={l} elevation={0} className="rounded-2xl border border-slate-200 p-5"><Typography className="text-sm font-semibold text-slate-500">{l}</Typography><Typography variant="h5" className="mt-2 font-black">{num(v)}</Typography></Paper>)}</div>
 <div className="grid grid-cols-1 gap-5 lg:grid-cols-3 mb-5">{[["Discount Given",o.discountAmount],["Gross Order Amount",o.grossOrderAmount],["Final Paid Amount",o.finalPaidAmount]].map(([l,v])=><Paper key={l} elevation={0} className="rounded-2xl border border-slate-200 p-5"><Typography className="text-sm font-semibold text-slate-500">{l}</Typography><Typography variant="h5" className="mt-2 font-black">{money(v)}</Typography></Paper>)}</div>
 <div className="grid grid-cols-1 gap-5 lg:grid-cols-2"><Paper elevation={0} className="rounded-2xl border border-slate-200 p-5"><Typography variant="h6" className="font-extrabold mb-4">Top Promo Codes</Typography><Stack spacing={1.5}>{(data?.topCodes||[]).map(x=><Box key={x.promoCodeId} className="rounded-xl border border-slate-100 p-3"><div className="flex justify-between gap-3"><Typography className="font-extrabold">{x.code}</Typography><Typography className="font-bold">{num(x.redemptions)} uses</Typography></div><Typography variant="body2" className="text-slate-500">Discount {money(x.discountAmount)} · Paid {money(x.finalAmount)}</Typography></Box>)}{!data?.topCodes?.length&&<Typography className="text-slate-400">No redemptions in this period.</Typography>}</Stack></Paper>
 <Paper elevation={0} className="rounded-2xl border border-slate-200 p-5"><div className="flex items-center justify-between mb-4"><Box><Typography variant="h6" className="font-extrabold">Admin Audit Trail</Typography><Typography variant="body2" className="text-slate-500">Recent promo management actions</Typography></Box><HistoryOutlined className="text-slate-400"/></div><Stack spacing={1.2}>{audit.map(x=><Box key={x.id} className="rounded-xl border border-slate-100 p-3"><div className="flex justify-between gap-3"><Typography className="font-bold">{x.action.toUpperCase()} · {x.code}</Typography><Typography variant="caption" className="text-slate-400">{new Date(x.createdAt).toLocaleString()}</Typography></div><Typography variant="body2" className="text-slate-500">By {x.actor?.name||x.actor?.email||"Administrator"}</Typography></Box>)}{!audit.length&&<Typography className="text-slate-400">No audit events yet.</Typography>}</Stack></Paper></div>
 </Box></Box>;
}
