const router=require('express').Router()
const c=require('../controllers/adminController')
router.get('/dashboard',c.dashboard)
router.get('/quizzes',c.listQuizzes)
router.post('/quizzes',c.createQuiz)
router.get('/quizzes/:quizId',c.getQuiz)
router.patch('/quizzes/:quizId',c.updateQuiz)
router.delete('/quizzes/:quizId',c.archiveQuiz)
router.get('/quizzes/:quizId/questions',c.listQuestions)
router.post('/quizzes/:quizId/questions',c.createQuestion)
router.patch('/questions/:questionId',c.updateQuestion)
router.delete('/questions/:questionId',c.deactivateQuestion)
router.get('/participants',c.listParticipants)
router.get('/attempts',c.listAttempts)
router.get('/results',c.listResults)
module.exports=router