import { Router } from "express";
import authRoutes from "./auth.routes.js";
import courseRoutes from "./course.routes.js";
import paymentRoutes from "./payment.routes.js";
import promoCodeRoutes from "./promoCode.routes.js";
import learningRoutes from "./learning.routes.js";
import progressRoutes from "./progress.routes.js";
import videoRoutes from "./video.routes.js";
import assessmentRoutes from "./assessment.routes.js";
import dashboardRoutes from "./dashboard.routes.js";
import certificateRoutes from "./certificate.routes.js";
import notificationRoutes from "./notification.routes.js";
import profileRoutes from "./profile.routes.js";
import supportRoutes from "./support.routes.js";
import contactMessageRoutes from "./contactMessage.routes.js";
import subscriberRoutes from "./subscriber.routes.js";
import dsaRoutes from "./dsa.routes.js";
import dsaPaymentRoutes from "./dsa.payment.routes.js";
import dsaPhase14Routes from "./dsa.phase14.routes.js";
import dsaSubmissionRoutes from "./dsa.submission.routes.js";
import dsaLeaderboardRoutes from "./dsa.leaderboard.routes.js";
import adminDsaRoutes from "./admin.dsa.routes.js";
import adminDsaChallengeRoutes from "./admin.dsa.challenge.routes.js";
import adminCourseRoutes from "./admin.course.routes.js";
import adminUserRoutes from "./admin.user.routes.js";
import adminPurchaseRoutes from "./admin.purchase.routes.js";
import adminProgressRoutes from "./admin.progress.routes.js";
import adminCertificateRoutes from "./admin.certificate.routes.js";
import adminNotificationRoutes from "./admin.notification.routes.js";
import adminAnalyticsRoutes from "./admin.analytics.routes.js";
import adminSupportRoutes from "./admin.support.routes.js";
import adminAssessmentRoutes from "./admin.assessment.routes.js";
import adminMessageRoutes from "./admin.message.routes.js";
import adminSubscriberRoutes from "./admin.subscriber.routes.js";
import adminPromoCodeRoutes from "./admin.promoCode.routes.js";
import referralRoutes from "./referral.routes.js";
import aiRoutes from "./ai.routes.js";
import aiConversationRoutes from "./aiConversation.routes.js";
import referralPayoutDestinationRoutes from "./referralPayoutDestination.routes.js";
import adminReferralPayoutRoutes from "./admin.referralPayout.routes.js";

const router = Router();
router.get("/", (req, res) => res.status(200).json({ success: true, message: "ApnaAcademy API v1 is working 🚀" }));
router.use("/auth", authRoutes);
router.use("/ai", aiRoutes);
router.use("/ai/conversations", aiConversationRoutes);
router.use("/courses", courseRoutes);
router.use("/payments", paymentRoutes);
router.use("/promocodes", promoCodeRoutes);
router.use("/referrals", referralRoutes);
router.use("/referrals/payout-destination", referralPayoutDestinationRoutes);
router.use("/learning", learningRoutes);
router.use("/progress", progressRoutes);
router.use("/videos", videoRoutes);
router.use("/assessment", assessmentRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/certificates", certificateRoutes);
router.use("/notifications", notificationRoutes);
router.use("/profile", profileRoutes);
router.use("/support", supportRoutes);
router.use("/messages", contactMessageRoutes);
router.use("/subscribers", subscriberRoutes);
router.use("/dsa", dsaRoutes);
router.use("/dsa/payments", dsaPaymentRoutes);
router.use("/dsa", dsaPhase14Routes);
router.use("/dsa/submissions", dsaSubmissionRoutes);
router.use("/dsa/leaderboard", dsaLeaderboardRoutes);
router.use("/admin/dsa", adminDsaRoutes);
router.use("/admin/dsa", adminDsaChallengeRoutes);
router.use("/admin/courses", adminCourseRoutes);
router.use("/admin/users", adminUserRoutes);
router.use("/admin/purchases", adminPurchaseRoutes);
router.use("/admin/progress", adminProgressRoutes);
router.use("/admin/certificates", adminCertificateRoutes);
router.use("/admin/notifications", adminNotificationRoutes);
router.use("/admin/analytics", adminAnalyticsRoutes);
router.use("/admin/support", adminSupportRoutes);
router.use("/admin/assessments", adminAssessmentRoutes);
router.use("/admin/messages", adminMessageRoutes);
router.use("/admin/subscribers", adminSubscriberRoutes);
router.use("/admin/promocodes", adminPromoCodeRoutes);
router.use("/admin/referral-payouts", adminReferralPayoutRoutes);
router.use("/admin/ai", adminAIRoutes);

export default router;
