import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowForward, ArrowUpward, Code, DesignServices, Email, Groups, LinkedIn, LocationOn, Phone, Send, School, Star, Storage, WorkOutline } from "@mui/icons-material";
import api from "../services/api";

const TEAM = [
  { name: "Dilkhush Kumar", role: "Founder & Full Stack Developer", bio: "Passionate about building scalable web applications and helping students achieve their dreams through practical learning.", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=88", icon: Code, github: "https://github.com/dk5847001-stack", linkedin: "https://www.linkedin.com/in/dilkhush-kumar-43a426372", tone: "bg-blue-50 text-blue-600" },
  { name: "Priya Sharma", role: "Frontend Developer", bio: "Creates beautiful and responsive user experiences with modern web technologies.", image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=88", icon: DesignServices, github: "https://github.com", linkedin: "https://www.linkedin.com", tone: "bg-violet-50 text-violet-600" },
  { name: "Rohit Verma", role: "Backend Developer", bio: "Builds powerful and secure APIs, databases and system infrastructure.", image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=88", icon: Storage, github: "https://github.com", linkedin: "https://www.linkedin.com", tone: "bg-indigo-50 text-indigo-600" },
  { name: "Sneha Patel", role: "UI/UX Designer", bio: "Designs intuitive and modern interfaces for seamless learning experiences.", image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=88", icon: DesignServices, github: "https://github.com", linkedin: "https://www.linkedin.com", tone: "bg-pink-50 text-pink-600" },
];
const SUBJECTS = ["Course enquiry", "Account & login", "Payment & purchase", "Certificate", "Internship program", "Technical support", "Other"];

export default function AboutPremium() {
  const [form, setForm] = useState({ name: "", email: "", subject: "", message: "" });
  const [loading, setLoading] = useState(false);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const change = (e) => { setForm((v) => ({ ...v, [e.target.name]: e.target.value })); setNotice(""); setError(""); };
  const submit = async (e) => {
    e.preventDefault();
    const data = { name: form.name.trim(), email: form.email.trim(), subject: form.subject.trim(), message: form.message.trim() };
    if (data.name.length < 2 || !/^\S+@\S+\.\S+$/.test(data.email) || data.subject.length < 3 || data.message.length < 10) { setError("Please enter valid details and a message of at least 10 characters."); return; }
    try { setLoading(true); await api.post("/messages", data); setForm({ name: "", email: "", subject: "", message: "" }); setNotice("Message sent successfully. Our team will review it soon."); }
    catch (err) { setError(err?.response?.data?.message || "Unable to send your message. Please try again."); }
    finally { setLoading(false); }
  };
  return <main className="min-h-screen overflow-x-hidden bg-white text-slate-900">
    <section className="relative overflow-hidden bg-gradient-to-br from-blue-50 via-white to-indigo-50/70">
      <div className="absolute -left-28 top-10 h-72 w-72 rounded-full bg-blue-200/30 blur-3xl" /><div className="absolute -right-24 bottom-0 h-80 w-80 rounded-full bg-indigo-200/30 blur-3xl" />
      <div className="relative mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 sm:py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24">
        <div><span className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3.5 py-1.5 text-xs font-extrabold text-blue-700"><Groups fontSize="small" />About Us</span><h1 className="mt-6 text-4xl font-black leading-[1.05] tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">Building a Better<br /><span className="text-blue-600">Learning</span> Future</h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-600 sm:text-lg">At ApnaAcademy, we are passionate about creating opportunities for students to learn, build skills and achieve their career goals through practical, hands-on learning.</p><div className="mt-8 flex flex-wrap gap-x-7 gap-y-4">{[["10K+","Students",School],["50+","Courses",WorkOutline],["4.8/5","Average Rating",Star]].map(([value,label,Icon])=><div key={label} className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-blue-100 text-blue-600"><Icon fontSize="small" /></span><span><b className="block text-sm font-black">{value}</b><small className="text-[11px] text-slate-500">{label}</small></span></div>)}</div></div>
        <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-5 rounded-[2.5rem] bg-blue-100/50 blur-2xl" /><div className="relative rounded-3xl border border-white bg-white p-2 shadow-[0_25px_70px_rgba(15,23,42,.12)]"><img src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=88" alt="Students learning together" className="aspect-[4/3] w-full rounded-[1.35rem] object-cover" /></div></div>
      </div>
    </section>

    <section className="bg-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-20 lg:px-8"><div className="mx-auto max-w-2xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3.5 py-1.5 text-xs font-extrabold text-blue-700"><Groups fontSize="small" />Our Team</span><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Meet Our <span className="text-blue-600">Amazing Team</span></h2><p className="mt-4 text-sm leading-7 text-slate-500 sm:text-base">We are a diverse team of passionate learners, developers and educators working together to build the best learning experience for you.</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{TEAM.map(({name,role,bio,image,icon:Icon,github,linkedin,tone})=><article key={name} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-[0_20px_45px_rgba(15,23,42,.10)]"><div className="relative overflow-hidden bg-slate-100"><img src={image} alt={`${name} - ${role}`} loading="lazy" className="aspect-[4/3] w-full object-cover transition duration-500 group-hover:scale-105" /><span className={`absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-xl border border-white/80 bg-white/90 shadow-sm ${tone}`}><Icon fontSize="small" /></span></div><div className="p-5"><h3 className="text-base font-black">{name}</h3><p className="mt-1 text-xs font-bold text-blue-600">{role}</p><p className="mt-3 text-sm leading-6 text-slate-500">{bio}</p><div className="mt-5 flex gap-2"><a href={github} target="_blank" rel="noreferrer" aria-label={`${name} GitHub`} className="grid h-8 w-8 place-items-center rounded-full bg-slate-50 text-slate-700 transition hover:bg-blue-50 hover:text-blue-600"><Code fontSize="small" /></a><a href={linkedin} target="_blank" rel="noreferrer" aria-label={`${name} LinkedIn`} className="grid h-8 w-8 place-items-center rounded-full bg-slate-50 text-slate-700 transition hover:bg-blue-50 hover:text-blue-600"><LinkedIn fontSize="small" /></a></div></div></article>)}</div></div></section>

    <section className="border-y border-blue-100 bg-gradient-to-b from-blue-50/70 to-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-20 lg:px-8"><div className="mb-9 max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3.5 py-1.5 text-xs font-extrabold text-blue-700"><Email fontSize="small" />Get In Touch</span><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Contact Us</h2><p className="mt-3 text-sm leading-7 text-slate-600 sm:text-base">Have questions, feedback, or need support? We&apos;re here to help! Send us a message and we&apos;ll get back to you as soon as possible.</p></div><div className="grid gap-7 lg:grid-cols-[1.12fr_.88fr]">
      <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_18px_50px_rgba(15,23,42,.06)] sm:p-7"><form onSubmit={submit} className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-xs font-extrabold text-slate-700">Full Name <em className="text-red-500">*</em></span><input required name="name" value={form.name} onChange={change} placeholder="Enter your name" className="w-full rounded-xl border border-slate-200 px-3.5 py-3 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10" /></label><label><span className="mb-2 block text-xs font-extrabold text-slate-700">Email Address <em className="text-red-500">*</em></span><input required type="email" name="email" value={form.email} onChange={change} placeholder="Enter your email" className="w-full rounded-xl border border-slate-200 px-3.5 py-3 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10" /></label></div><label className="block"><span className="mb-2 block text-xs font-extrabold text-slate-700">Subject <em className="text-red-500">*</em></span><select required name="subject" value={form.subject} onChange={change} className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"><option value="">Select a subject</option>{SUBJECTS.map((s)=><option key={s}>{s}</option>)}</select></label><label className="block"><span className="mb-2 block text-xs font-extrabold text-slate-700">Message <em className="text-red-500">*</em></span><textarea required minLength={10} maxLength={5000} rows={5} name="message" value={form.message} onChange={change} placeholder="Your message here..." className="w-full resize-y rounded-xl border border-slate-200 px-3.5 py-3 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10" /></label>{error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs font-bold text-red-700">{error}</div>}{notice&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-bold text-emerald-700">{notice}</div>}<button disabled={loading} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-extrabold text-white transition hover:bg-blue-700 disabled:opacity-60">{loading?"Sending...":"Send Message"}<Send fontSize="small" /></button></form></div>
      <div className="space-y-5"><div className="relative overflow-hidden rounded-3xl border border-white bg-white p-2 shadow-[0_18px_50px_rgba(15,23,42,.08)]"><img src="https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=88" alt="Modern learning workspace" loading="lazy" className="aspect-[5/3] w-full rounded-[1.35rem] object-cover" /><div className="absolute bottom-5 left-5 rounded-2xl border border-white/70 bg-white/90 px-4 py-3 shadow-lg backdrop-blur"><p className="text-xs font-black">Let&apos;s Build Your Future Together</p><p className="mt-1 text-[11px] text-slate-500">We&apos;re here when you need us.</p></div></div><div className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm sm:p-6"><div className="space-y-5"><a href="mailto:support@apnaacademy.in" className="flex items-start gap-3 no-underline"><span className="grid h-10 w-10 place-items-center rounded-full bg-blue-50 text-blue-600"><Email fontSize="small" /></span><span><b className="block text-xs">Email Us</b><small className="text-xs text-slate-500">support@apnaacademy.in</small></span></a><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-blue-50 text-blue-600"><Phone fontSize="small" /></span><span><b className="block text-xs">Call Us</b><small className="text-xs text-slate-500">+91 98765 43210</small></span></div><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-blue-50 text-blue-600"><LocationOn fontSize="small" /></span><span><b className="block text-xs">Location</b><small className="text-xs leading-5 text-slate-500">Noida, Uttar Pradesh, India</small></span></div></div></div></div>
    </div></div></section>

    <section className="bg-white"><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="flex flex-col items-start justify-between gap-5 rounded-3xl border border-blue-100 bg-gradient-to-r from-blue-50 to-indigo-50 p-7 sm:flex-row sm:items-center sm:p-9"><div><p className="text-lg font-black">Ready to start learning?</p><p className="mt-1 text-sm text-slate-500">Explore practical courses and build skills that move you forward.</p></div><Link to="/courses" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-extrabold text-white no-underline hover:bg-blue-700">Explore Courses <ArrowForward fontSize="small" /></Link></div></div></section>
    <button type="button" onClick={() => window.scrollTo({top:0,behavior:"smooth"})} aria-label="Back to top" className="fixed bottom-5 right-5 z-20 grid h-10 w-10 place-items-center rounded-full border border-slate-200 bg-white text-slate-600 shadow-lg hover:text-blue-600"><ArrowUpward fontSize="small" /></button>
  </main>;
}