import { ArrowForward, AutoStoriesOutlined, CalendarMonthOutlined } from "@mui/icons-material";
import { Box, Card, CardContent, Chip, Container, Typography } from "@mui/material";

const posts=[
 {title:"How to Build Job-Ready Web Development Skills",date:"September 14, 2026",tag:"Career",excerpt:"A practical roadmap for learning frontend, backend, APIs, databases and real-world project development.",body:"Job-ready development comes from combining fundamentals with consistent project work. Start with HTML, CSS and JavaScript, then build React interfaces and Node.js APIs. Add databases, authentication, deployment and Git workflows. The strongest portfolio projects solve a real problem and demonstrate clean architecture, security and usability."},
 {title:"Why Project-Based Learning Works",date:"September 10, 2026",tag:"Learning",excerpt:"Move from passive tutorials to structured projects, assessments and measurable progress.",body:"Project-based learning turns concepts into decisions. Break a project into milestones, document what you learn, test each feature and review your implementation. Short feedback loops make it easier to identify gaps and build confidence."},
 {title:"A Better Way to Prepare for Technical Interviews",date:"September 5, 2026",tag:"Interview",excerpt:"Build a balanced routine across DSA, CS fundamentals, projects and communication.",body:"Interview preparation works best when it is deliberate. Practice DSA regularly, revise core CS concepts, understand every project on your resume and rehearse concise explanations. Track weak areas instead of repeating only comfortable questions."},
];
export default function Blog(){return <Box className="min-h-screen bg-slate-50 text-slate-900"><section className="border-b border-slate-200 bg-white"><Container maxWidth="lg"><div className="py-16 text-center sm:py-20"><Chip icon={<AutoStoriesOutlined/>} label="ApnaAcademy Blog" variant="outlined" className="!border-blue-200 !bg-blue-50 !font-bold !text-blue-700"/><Typography component="h1" className="!mx-auto !mt-5 !max-w-4xl !text-4xl !font-black !tracking-tight !text-slate-950 sm:!text-5xl">Learn smarter. Build better. Grow faster.</Typography><Typography className="!mx-auto !mt-4 !max-w-2xl !text-base !leading-8 !text-slate-600 sm:!text-lg">Practical insights on technology, projects, learning and career growth.</Typography></div></Container></section><Container maxWidth="lg"><div className="grid gap-6 py-12 md:grid-cols-2 lg:grid-cols-3">{posts.map(post=><Card key={post.title} elevation={0} className="!flex !h-full !flex-col !rounded-3xl !border !border-slate-200 !bg-white !shadow-sm"><CardContent className="!flex !h-full !flex-col !p-6"><Chip size="small" label={post.tag} className="!w-fit !bg-blue-50 !font-bold !text-blue-700"/><Typography component="h2" className="!mt-5 !text-xl !font-black !leading-snug">{post.title}</Typography><div className="mt-3 flex items-center gap-2 text-xs font-semibold text-slate-400"><CalendarMonthOutlined sx={{fontSize:16}}/>{post.date}</div><Typography className="!mt-4 !text-sm !leading-7 !text-slate-600">{post.excerpt}</Typography><details className="mt-4"><summary className="flex cursor-pointer items-center gap-2 text-sm font-extrabold text-blue-600">Read article <ArrowForward sx={{fontSize:16}}/></summary><Typography className="!mt-4 !text-sm !leading-7 !text-slate-600">{post.body}</Typography></details></CardContent></Card>)}</div></Container></Box>}
