import { Box, Container, Typography } from "@mui/material";

const sections=[
 ["1. Information We Collect","We may collect information you provide when you create an account, purchase a course, contact support, subscribe to updates or use learning features. This can include your name, email address, account details, purchase information and messages you send us."],
 ["2. How We Use Information","We use information to provide and secure the platform, process purchases, provide course access, support learners, maintain certificates, communicate important service updates and improve our services."],
 ["3. Payments","Online payments are processed through our payment provider. ApnaAcademy does not need to store your complete card or banking credentials. Payment records such as order identifiers, payment status and transaction metadata may be retained for reconciliation, fraud prevention and support."],
 ["4. Cookies and Local Storage","The website may use cookies required for authentication and local browser storage for preferences such as theme settings. These technologies help keep sessions secure and provide a consistent experience."],
 ["5. Data Sharing","We do not sell personal information. Information may be shared with service providers only when necessary to operate features such as hosting, payments, authentication, video delivery or platform security, subject to their applicable terms."],
 ["6. Security","We use reasonable technical and organizational safeguards designed to protect account and transaction information. No internet service can guarantee absolute security, so users should keep credentials confidential and report suspicious activity promptly."],
 ["7. Data Retention and Requests","We retain information for as long as reasonably necessary for account operation, legal, security, payment and support purposes. For privacy-related requests, contact our support team with sufficient information to identify the request."],
 ["8. Children","The service is intended for users who can legally use online educational services in their jurisdiction. We do not knowingly collect personal information from children where collection is prohibited by applicable law."],
 ["9. Policy Updates","We may update this policy when our services, legal obligations or security practices change. The latest version published on this page will apply from its stated update date."],
];
export default function PrivacyPolicy(){return <Box className="min-h-screen bg-slate-50 text-slate-900"><Container maxWidth="md"><div className="py-12 sm:py-16"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-blue-600">Legal</p><Typography component="h1" className="!mt-2 !text-4xl !font-black !tracking-tight !text-slate-950">Privacy Policy</Typography><Typography className="!mt-3 !text-sm !text-slate-500">Last updated: September 14, 2026</Typography><Typography className="!mt-6 !text-sm !leading-7 !text-slate-600">This Privacy Policy explains how ApnaAcademy handles information when you use our website, learning platform and related services.</Typography><div className="mt-8 space-y-7">{sections.map(([title,text])=><section key={title}><Typography component="h2" className="!text-lg !font-black !text-slate-950">{title}</Typography><Typography className="!mt-2 !text-sm !leading-7 !text-slate-600">{text}</Typography></section>)}</div><div className="mt-9 rounded-2xl bg-blue-50 p-5"><Typography className="!text-sm !font-bold !text-blue-950">Privacy contact</Typography><Typography className="!mt-1 !text-sm !text-blue-800">For questions about privacy or your information, email support@apnaacademy.in.</Typography></div></div></div></Container></Box>}
