import { Box, Container, Typography } from "@mui/material";

const sections=[
 ["1. General Policy","Because digital courses and learning access can begin immediately after purchase, refund eligibility depends on the circumstances of the request and the amount of course access or consumption already used."],
 ["2. When You May Request a Refund","If you experience a duplicate charge, an incorrect charge, a material technical issue that prevents access, or another legitimate payment problem, contact support as soon as possible with your registered email and payment/order details."],
 ["3. Course Access","Requests made after substantial course consumption, repeated use of protected learning content, completion of significant modules, or use of downloadable/digital benefits may not qualify for a refund. Access may be reviewed using purchase and learning records."],
 ["4. Duplicate or Failed Payments","If your bank/payment provider shows a debit but the ApnaAcademy order was not successfully completed, the transaction can be reviewed against the payment gateway record. Eligible reversals are processed through the original payment method where supported."],
 ["5. How to Request","Email support@apnaacademy.in with your registered email, order/payment identifier, purchase date and a clear description of the issue. Never send full card numbers, CVV, passwords or OTPs."],
 ["6. Review and Decision","Each request is reviewed using the applicable purchase, access and payment records. If approved, processing time may depend on the payment provider or bank. We will communicate the outcome using the contact information associated with the request."],
 ["7. Changes","We may update this Refund Policy when our products, payment flows or legal requirements change. The version published on this page is the current version."],
];
export default function RefundPolicy(){return <Box className="min-h-screen bg-slate-50 text-slate-900"><Container maxWidth="md"><div className="py-12 sm:py-16"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-blue-600">Legal</p><Typography component="h1" className="!mt-2 !text-4xl !font-black !tracking-tight !text-slate-950">Refund Policy</Typography><Typography className="!mt-3 !text-sm !text-slate-500">Last updated: September 14, 2026</Typography><Typography className="!mt-6 !text-sm !leading-7 !text-slate-600">This policy describes how ApnaAcademy handles refund requests for digital courses and related online learning purchases.</Typography><div className="mt-8 space-y-7">{sections.map(([title,text])=><section key={title}><Typography component="h2" className="!text-lg !font-black !text-slate-950">{title}</Typography><Typography className="!mt-2 !text-sm !leading-7 !text-slate-600">{text}</Typography></section>)}</div><div className="mt-9 rounded-2xl bg-amber-50 p-5"><Typography className="!text-sm !font-bold !text-amber-950">Important</Typography><Typography className="!mt-1 !text-sm !leading-6 !text-amber-900">Refund eligibility can depend on the product, payment status, course usage and applicable consumer laws. This page does not remove any rights that cannot lawfully be excluded.</Typography></div></div></div></Container></Box>}
